name: Get deploy tag
description: Return deploy tag
inputs:
  environment:
    description: "environment"
    required: true
outputs:
  tag:
    description: deploy tag
    value: ${{ steps.tag.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Create tag
      id: tag
      shell: bash
      run: |
        echo "::set-output name=tag::${{ github.event.number ? format('pr-{0}', github.event.number) : inputs.environment }}"