name: Upload docker images
description: Uploads NextJs Apps docker images to artifactory
inputs:
  apps:
    description: Array of NextJs apps
    required: true
  action-if-missing:
    description: Action when image is missing (ignore | warning | error)
    required: false
    default: warning
  local-tag:
    description: local tag name
    required: false
    default: latest
  remote-tag:
    description: remote tag name i.e pr-1234
    required: true
  registry-url:
    description: Registry to upload images to
    required: false
    default: tsefe-docker.jfrog.teliacompany.io
runs:
  using: node16
  main: dist/index.js
