name: "rush publish"
inputs:
  authorName:
    required: true
  authorEmail:
    required: true
  npmUsername:
    required: true
  npmPassword:
    required: true
  targetBranch:
    required: false
    default: main
runs:
  using: "composite"
  steps:
    - name: Setup git user
      run: |
        git config --local user.name "${{ inputs.authorName }}"
        git config --local user.email "${{ inputs.authorEmail }}"
      shell: bash
    - name: Get npm auth
      id: npm_auth
      run: echo "::set-output name=token::$(echo ${{ inputs.npmUsername }}:${{ inputs.npmPassword }} | base64 -w 0)"
      shell: bash
    - name: Publish
      run: |
        node common/scripts/install-run-rush.js version --bump --target-branch ${{ inputs.targetBranch }}
        node common/scripts/install-run-rush.js publish --publish --include-all
      shell: bash
      env:
        NPM_CONFIG_NOPROXY: jfrog.teliacompany.io
        NPM_CONFIG__AUTH: ${{ steps.npm_auth.outputs.token }}
