name: 'rush publish'
inputs:
  authorName:
    required: true
  authorEmail:
    required: true
  npmUsername:
    required: true
  npmPassword:
    required: true
  targetBranch:
    required: false
    default: main
runs:
  using: "composite"
  steps:
    - name: Setup git user
      run: |
        git config --local user.name "${{ inputs.authorName }}"
        git config --local user.email "${{ inputs.authorEmail }}"
      shell: bash
    - name: Set npm auth
      run: |
        curl -u ${{ inputs.npmUsername }}:${{ inputs.npmPassword }} https://jfrog.teliacompany.io/artifactory/api/npm/auth > ~/.npmrc
        more ~/.npmrc
      shell: bash
    - name: hack
      run: |
        echo ${{ toJson(inputs.npmPassword) }} > test.json
        more test.json
      shell: bash
    - name: Publish
      run: |
        node common/scripts/install-run-rush.js publish --publish --include-all
      shell: bash
      env:
        NPM_CONFIG_NOPROXY: jfrog.teliacompany.io
