name: "rush publish"
inputs:
  author-name:
    required: true
  author-email:
    required: true
  npm-username:
    required: true
  npm-password:
    required: true
  target-branch:
    required: false
    default: main
runs:
  using: "composite"
  steps:
    - name: Setup git user
      run: |
        git config --local user.name "${{ inputs.author-name }}"
        git config --local user.email "${{ inputs.author-email }}"
      shell: bash
    - name: Get npm auth
      id: npm_auth
      run: echo "::set-output name=token::$(echo ${{ inputs.npm-username }}:${{ inputs.npm-password }} | base64 -w 0)"
      shell: bash
    - name: Publish
      run: |
        node common/scripts/install-run-rush.js version --bump --target-branch ${{ inputs.target-branch }}
        node common/scripts/install-run-rush.js publish --publish --include-all
      shell: bash
      env:
        NPM_CONFIG_NOPROXY: jfrog.teliacompany.io
        NPM_CONFIG__AUTH: ${{ steps.npm_auth.outputs.token }}
