name: Download and parse workflow info
description: Download and parse workflow info
inputs:
  token:
    description: Github token
    required: false
    default: ${{ github.token }}
  fail_if_absent:
    description: Fail if any key in "fail_if_absent" is missing.from the workflow info JSON
    required: false
outputs:
  environment:
    description: environment
  author_email:
    description: author_email
runs:
  using: node16
  main: dist/index.js
