name: Validate PR title
description: Validate pull request title
inputs:
  token:
    description: Token
    required: true
  owner:
    description: Owner
    required: true
  repository:
    description: Repository
    required: true
  pullRequestNumber:
    description: Pull request number
    required: true
  title:
    description: A pull request title to validate
    required: true
runs:
  using: node12
  main: dist/index.js
