name: Validate PR title
description: Validate pull request title
inputs:
  token:
    description: GitHub access token
    default: ${{ github.token }}
  owner:
    description: Owner, e.g. 'telia-company'
    default: ${{ github.repository_owner }}
  repository:
    description: Repository, e.g. 'teliasaurus'
    default: ${{ github.event.repository.name }}
  pull-request-number:
    description: Pull request number
    default: ${{ github.event.number }}
runs:
  using: node12
  main: dist/index.js
