name: Pull request notification
description: Notify pull request author
inputs:
  github-comment:
    required: false
  github-token:
    required: true
  pr-number:
    required: true
  slack-message:
    required: true
  slack-token:
    required: true
runs:
  using: composite
  steps:
    - name: Look up GitHub user
      id: github_user
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr-number }},
          });

          const { data: user } = await github.rest.users.getByUsername({
            username: pullRequest.user.login
          });

          return user;
    - name: Look up Slack user
      id: slack_user
      uses: telia-actions/look-up-slack-user@v8
      with:
        email: ${{ fromJson(steps.github_user.outputs.result).email }}
        token: ${{ inputs.slack-token }}
    - name: Post to a Slack user
      uses: telia-actions/slack-github-action@v1.17.0
      if: steps.slack_user.outputs.user != ''
      with:
        channel-id: ${{ fromJson(steps.slack_user.outputs.user).id }}
        slack-message: ${{ inputs.slack-message }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-token }}
    - name: Create PR comment
      if: ${{ inputs.github-comment != '' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          return await github.rest.issues.createComment({
            issue_number: ${{ inputs.pr-number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "${{ inputs.github-comment }}"
          });
