name: Create slack message payload
description: Upload to generic JFrog Artifactory repository
inputs:
  token:
    description: Github token
    required: false
    default: ${{ github.token }}
outputs:
  payload:
    description: Slack message payload  
runs:
  using: node16
  main: dist/index.js
