name: Create slack message payload
description: Create slack message payload
inputs:
  token:
    description: Github token
    required: false
    default: ${{ github.token }}
  environment:
    description: environment
    required: true
outputs:
  payload:
    description: Slack message payload  
runs:
  using: node16
  main: dist/index.js
