name: Test WofklowInfo
on:
  workflow_run:
    workflows: [Mocked failure, Mocked success]
    types: [completed]
jobs:
  get_workflow_info:
    runs-on: ubuntu-latest
    steps:
      - name: Create payload for slack-github-action
        id: workflowInfo
        uses: telia-actions/fft-actions/actions/get-workflow-info@main
        with:
          fail_if_absent: '["environment", "author_email"]'
      - name: Echo values
        run: |
          echo ${{ steps.workflowInfo.outputs.author_email }}
          echo ${{ steps.workflowInfo.outputs.environment }}

