name: ECS service update / Tests
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - actions/update-ecs-services/**
      - .github/workflows/test-update-ecs-services.yaml
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Do a dry-run
        uses: ./actions/update-ecs-services
        with:
          aws-access-key-id: "ACCESS_KEY"
          aws-secret-access-key: "SECRET_KEY"
          aws-session-token: "SESSION"
          env-name: "environment"
          service-names: '["service-1", "service-2"]'
          dry-run: true
