name: Test create tag action
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
jobs:
  get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: telia-actions/fft-actions/actions/get-deploy-tag@f159d20f61878cb220b514e9a585838df28b9487
        with:
          deploy_environment: dev
          pr_number: ${{ github.event.number }}
      - name: Echo value
        run: |
          echo ${{ steps.tag.outputs.tag }}
